#pragma once

#define FONT_SIZE_PIXELS_BIGGEST  65
#define FONT_SIZE_PIXELS_BIG      50
#define FONT_SIZE_PIXELS_NORMAL   44
#define FONT_SIZE_PIXELS_SMALL    38
#define FONT_SIZE_PIXELS_SMALLER  35
#define FONT_SIZE_PIXELS_SMALLEST 32
